// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhpseifvsclqxiizwqnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhocHNlaWZ2c2NscXhpaXp3cW5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4ODk1MTMsImV4cCI6MjA3MzQ2NTUxM30.lZDLpqV-RylNmc37CqGEvqz9E_gVvoVfdWL2jXQX0gQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});